---
default_config:

automation ui: !include "automations.yaml"

logger:
  default: "info"
  logs:
    custom_components.ui_lovelace_minimalist: "debug"

sensor:
  platform: "prixCarburant"
  maxDistance: 20
